name: kkservices
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.2.0
  flutter_map: any

  animated_text_kit: ^4.2.1
  animated_textformfields: ^1.0.1
  flutter_animated_button: ^2.0.0
  email_validator: ^2.0.1
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^0.19.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  table_calendar: ^3.0.4
  cloud_firestore: ^3.1.10
  fluttertoast: ^8.0.9
  flutter_stripe: ^2.5.0
  get: 4.6.1

  #format date and time
  intl: ^0.17.0
  google_maps_flutter: ^2.1.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: ubuntu
    fonts:
      - asset: assets\Ubuntu-Regular.ttf

